version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  app-cpu:
    build: .
    environment:
      - PYTHONPATH=/app
      - LOCAL_LANGUAGE_MODEL=gpt2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BLS_API_KEY=${BLS_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - STARTUP_TOPIC=${STARTUP_TOPIC:-AI/ML}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: python -m rag_startups.main generate --market --num 3 --topic "${STARTUP_TOPIC:-AI/ML}"

volumes:
  redis-data:
