site_name: RAG Startups
site_description: Documentation for the RAG-based startup ideas generation project
repo_url: https://github.com/yourusername/rag_startups
docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
  - autorefs
  - include-markdown:
      preserve_includer_indent: true
      dedent: true
      comments: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - User Guide:
    - Overview: user-guide/index.md
    - Configuration: configuration.md
    - Examples: examples.md
    - Market Analysis: market_analysis.md
  - API Reference: api.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
