name: Mirror Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Sync repositories
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/valginer0/rag_startups"
          source_branch: "main"
          destination_repo: "https://github.com/valginer0/RAGVenture"
          destination_branch: "main"
          github_token: ${{ secrets.MIRROR_SSH_KEY }}
