name: Mirror Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to public repository
        run: |
          git remote add public https://${{ secrets.MIRROR_SSH_KEY }}@github.com/valginer0/RAGVenture.git
          git fetch --unshallow origin
          git push --force public main:main
