name: Mirror Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to public repository
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_SSH_KEY }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add public "https://${GITHUB_TOKEN}@github.com/valginer0/RAGVenture.git"
          git fetch origin
          git push --force public main:main
