name: Mirror Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Public Repository
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_SSH_KEY }}
        run: |
          git remote add public https://${{ secrets.MIRROR_SSH_KEY }}@github.com/valginer0/RAGVenture.git
          git push public main:main --force
