name: Mirror Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.MIRROR_PAT }}
          repository: valginer0/rag_startups

      - name: Debug Git Remotes
        run: |
          git remote -v
          git branch -a
          git status
          echo "Current directory:"
          pwd
          ls -la

      - name: Mirror to public repository
        run: |
          git remote add public https://${{ secrets.MIRROR_PAT }}@github.com/valginer0/RAGVenture.git
          git push --force public main:main
